# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kylemanna/openvpn
  tag: 2.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 1194

dirPath:
  # The project dir.
  data: /tmp/docker-for-mac-openvpn
  # Local dir to hold generated files.
  local: /tmp/openvpn
  # Local dir to hold generated server configs.
  configs: /tmp/openvpn/configs
